services:
  db:
    container_name: db
    build:
      context: db
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"  # Port MySQL
    environment:
      - MYSQL_USER=wine_user
      - MYSQL_PASSWORD=secure_password
      - MYSQL_DATABASE=wine_cellar
      - MYSQL_ROOT_PASSWORD=root_password  # Obligatoire pour MySQL
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      # - postgres_data:/var/lib/postgresql/data  # Volume persistant pour la base de données
    networks:
      - backend    # La base de données est uniquement sur le réseau "backend"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"  # Mappe le port 5000 du conteneur au port 5000 de ta machine
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://wine_user:secure_password@db:3306/wine_cellar
    volumes:
      # - ./backend/code:/app:ro
        - ./backend/code:/app
    networks:
      - frontend   # Le backend est sur les réseaux "frontend" et "backend"
      - backend
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

# Définition des réseaux
networks:
  frontend:
    driver: bridge  # Réseau pour la communication entre frontend et backend
  backend:
    driver: bridge  # Réseau isolé pour la communication entre backend et db

# Définition des volumes
volumes:
  postgres_data:  # Volume persistant pour la base de données
